version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    container_name: elasticsearch
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ELASTIC_PASSWORD"=123456
    networks:
      elk:
        ipv4_address: 172.25.0.2
    restart: always

  logstash:
    build:
      context: logstash/
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - mysqllog:/xlogs/mysqllog:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    user: "root"
    networks:
      elk:
        ipv4_address: 172.25.0.3
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    build:
      context: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      elk:
        ipv4_address: 172.25.0.4
    depends_on:
      - elasticsearch
    restart: always

  metricbeat:
    build:
      context: metricbeat/
    container_name: metricbeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    user: "root"
    network_mode: host
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    command: -system.hostfs=/hostfs -e
    restart: always
  
  nginx:
    build:
      context: nginx/
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      elk:
        ipv4_address: 172.25.0.5
    depends_on:
      - kibana
    restart: always


  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: head
    ports:
      - 9100:9100
    volumes:
      - ./es-head/Gruntfile.js:/usr/src/app/Gruntfile.js
      - ./es-head/app.js:/usr/src/app/_site/app.js

  skywalking-oap:
    image: wutang/skywalking-oap:6.1.0
    container_name: skywalking-oap
    networks:
      - sc-net
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./data/skywalking/config:/apache-skywalking-apm-bin/config:ro

  skywalking-ui:
    image: wutang/skywalking-ui:6.1.0
    container_name: skywalking-ui
    networks:
      - sc-net
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 8080:8080
    environment:
      collector.ribbon.listOfServers: skywalking-oap:12800
volumes:
  esdata:
    driver: local
  

networks:
  elk:
    driver: bridge
    ipam:
      config:
       - subnet: 172.25.0.0/16
