version: '3'

services:
  elasticsearch:
    build:
      context: elasticsearch/
    container_name: es
    privileged: true
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ELASTIC_PASSWORD=123456"
    networks:
      - elk
    restart: always

  logstash:
    build:
      context: logstash/
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    user: "root"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  kibana:
    build:
      context: kibana/
    container_name: kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always

  metricbeat:
    build:
      context: metricbeat/
    container_name: metricbeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d:ro
      -  /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    user: "root"
    network_mode: "bridge"
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    command: -system.hostfs=/hostfs -e
    restart: always


  elasticsearch-head:
    image: mobz/elasticsearch-head:5
    container_name: head
    ports:
      - 9100:9100
    volumes:
      - ./es-head/Gruntfile.js:/usr/src/app/Gruntfile.js:ro
      - ./es-head/app.js:/usr/src/app/_site/app.js:ro

  skywalking-oap:
    image: apache/skywalking-oap-server:6.2.0
    container_name: skywalking-oap
    environment:
      - TZ=Asia/Shanghai
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./data/skywalking/config:/apache-skywalking-apm-bin/config:ro

  skywalking-ui:
    image: apache/skywalking-ui:6.2.0
    container_name: skywalking-ui
    networks:
      - elk
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap
    restart: always
    ports:
      - 8080:8080
    environment:
      security.user.admin.password: adminuser
      collector.ribbon.listOfServers: skywalking-oap:12800

volumes:
  esdata:
    driver: local
  

networks:
  elk:
    driver: bridge
    external: false
