FROM docker.elastic.co/elasticsearch/elasticsearch:6.4.2

LABEL maintainer="349514537@qq.com"

COPY ./config/elasticsearch.yml /usr/share/elasticsearch/conifg/elasticsearch.yml

RUN echo "Asia/Shanghai" > /etc/timezone